pragma Singleton
pragma ComponentBehavior: Bound

import QtQuick
import Quickshell
import Quickshell.Io
import Quickshell.Hyprland

import qs.config

/*
 * Sets Hyprland up for axiom (the Hyprland section, HyprlandConfig.mode).
 * One Lua "layer" (binds, required settings, themed borders, blur) reaches
 * Hyprland in one of three ways:
 *   detached  evaluated at runtime (hyprctl eval), again after every config
 *             reload, which drops it; binds on keys already taken are skipped
 *   included  written to $XDG_STATE_HOME/axiom/hyprland.lua, a module the
 *             user's hyprland.lua loads (includeLines)
 *   managed   written into ~/.config/hypr/hyprland.lua itself, with the
 *             Managed config, loading ~/.config/hypr/user/*.lua after it
 * Whenever the file isn't loaded (included but the lines are missing, or a
 * managed takeover refused), the runtime layer is applied instead, so axiom
 * still works, and `problem` says why.
 */
Singleton {
  id: root

  readonly property string mode: HyprlandConfig.mode
  // Why the chosen mode isn't in effect, or ""
  readonly property string problem: _problem
  property string _problem: ""

  readonly property string includePath: Paths.userStatePath + "hyprland.lua"
  readonly property string managedPath: Paths.hyprlandPath + "hyprland.lua"
  readonly property string userDir: Paths.hyprlandPath + "user"
  // What the user's hyprland.lua needs for the included mode
  readonly property string includeLines: `local ok, axiom = pcall(dofile, ${_lua(includePath)})\nif ok then axiom.setup() end`

  readonly property string _shellCommand: `qs -p '${Paths.axiomPath.replace(/\/$/, "")}'`
  readonly property string _header: "-- Generated by axiom"

  // --- The Lua layer ---

  // Actions (the schema's Hyprland.binds[].action) as IPC calls, with the
  // default label on the Keybinds page. I18n.tr isn't used: labels go to
  // Hyprland, like the user's own bind descriptions.
  readonly property var _actions: ({
      "launcher": ["appLauncher toggle", "App launcher"],
      "launcherSearch": ["appLauncher search {0}", "Launcher: {0}"],
      "overlay": ["overlay toggle", "Overlay"],
      "overlayPage": ["overlay page {0}", "Overlay: {0}"],
      "workspaceOverview": ["workspaceOverlay toggle", "Workspace overview"],
      "powerMenu": ["powermenu toggle", "Power menu"],
      "lock": ["lockscreen lock", "Lock"],
      "toggleDnd": ["notifications toggleDnd", "Do not disturb"],
      "clearNotifications": ["notifications clear", "Clear notifications"],
      "idleInhibit": ["idleInhibit toggle", "Caffeine"],
      "workspaceStep": ["workspaces step {0} go", "Workspace {0}"],
      "moveWindowStep": ["workspaces step {0} move", "Move window {0}"],
      "workspaceNth": ["workspaces nth {0} go", "Go to workspace {0}"],
      "moveWindowStepSilent": ["workspaces step {0} moveSilent", "Send window {0}"],
      "moveWindowNth": ["workspaces nth {0} move", "Move window to workspace {0}"],
      "moveWindowNthSilent": ["workspaces nth {0} moveSilent", "Send window to workspace {0}"]
    })

  // A Lua string literal
  function _lua(text) {
    return '"' + String(text).replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n") + '"';
  }

  // A single-quoted shell word
  function _shellWord(text) {
    return "'" + String(text).replace(/'/g, "'\\''") + "'";
  }

  function _hex(color) {
    return [color.r, color.g, color.b].map(v => Math.round(v * 255).toString(16).padStart(2, "0")).join("");
  }

  // The hl.bind() line for a configured bind, or "" when it's incomplete
  function _bindLua(bind) {
    const argument = String(bind.argument ?? "").trim();
    let command, label;
    if (bind.action === "exec") {
      command = argument;
      label = argument;
    } else {
      const action = _actions[bind.action];
      if (!action)
        return "";
      command = `${_shellCommand} ipc call ${action[0].replace("{0}", _shellWord(argument))}`;
      label = action[1].replace("{0}", argument);
    }
    if (!String(bind.key ?? "").trim() || !command || (_needsArgument(bind.action) && !argument))
      return "";
    // A "Section: Label" description picks its own section on the Keybinds
    // page; anything else goes under Axiom
    const own = String(bind.description ?? "").trim();
    const description = /^[^:]+: \S/.test(own) ? own : "Axiom: " + (own || label);
    return `hl.bind(${_lua(bind.key.trim())}, hl.dsp.exec_cmd(${_lua(command)}), { description = ${_lua(description)} })`;
  }

  function _needsArgument(action) {
    return action === "exec" || (_actions[action]?.[0] ?? "").includes("{0}");
  }

  function _requiredLua(withAnimation) {
    const lines = ["hl.config({ misc = { allow_session_lock_restore = true } })"];
    if (withAnimation)
      lines.push(`hl.animation({ leaf = "workspaces", enabled = true, speed = 4, bezier = "default", style = "slide" })`);
    return lines;
  }

  function _themeLua() {
    return [`hl.config({ general = { col = { active_border = "rgb(${_hex(Theme.borderFocus)})", inactive_border = "rgb(${_hex(Theme.border)})" } } })`];
  }

  function _blurLua() {
    return [`hl.layer_rule({ match = { namespace = "^axiom-(bar|edge-popout|launcher)$" }, blur = true, ignore_alpha = 0.2 })`];
  }

  function _indent(lines, prefix) {
    return lines.map(line => line === "" ? "" : prefix + line).join("\n");
  }

  // The included file: a module whose setup() applies what's enabled
  function moduleLua() {
    const binds = HyprlandConfig.binds.map(bind => _bindLua(bind)).filter(line => line !== "");
    const setup = [];
    if (HyprlandConfig.requiredSettings)
      setup.push("M.required()");
    setup.push("M.binds()");
    if (HyprlandConfig.theme)
      setup.push("M.theme()");
    if (HyprlandConfig.blur)
      setup.push("M.blur()");
    return `${_header} from its Hyprland settings, and rewritten whenever they
-- (or the theme) change: edit those, not this file.
--
-- Load it near the top of hyprland.lua, so what follows overrides it:
--   ${includeLines.replace("\n", "\n--   ")}
-- setup() applies everything enabled in axiom's settings; call the parts
-- instead to pick. hl.unbind("KEY") after it frees one of axiom's keys.
local M = {}

-- Session lock restore and a workspaces animation (axiom's grid slides)
function M.required()
${_indent(_requiredLua(true), "  ")}
end

function M.binds()
${_indent(binds, "  ")}
end

-- Window borders from the axiom theme
function M.theme()
${_indent(_themeLua(), "  ")}
end

-- Blur behind the bars, edge popouts and launcher
function M.blur()
${_indent(_blurLua(), "  ")}
end

function M.setup()
${_indent(setup, "  ")}
end

-- Lets axiom see that this file is loaded
AXIOM_INCLUDED = true

return M
`;
  }

  function _cursorLua(m) {
    if (!m.cursorTheme)
      return "";
    return `hl.env("XCURSOR_THEME", ${_lua(m.cursorTheme)})\nhl.env("XCURSOR_SIZE", ${_lua(String(m.cursorSize))})\n`;
  }

  // What the managed file runs once Hyprland has started
  function _startLua(m) {
    const lines = [];
    if (m.cursorTheme)
      lines.push(`hl.exec_cmd(${_lua(`hyprctl setcursor ${_shellWord(m.cursorTheme)} ${m.cursorSize}`)})`);
    lines.push(`hl.exec_cmd(${_lua(_shellCommand)})`);
    return lines;
  }

  // The managed hyprland.lua
  function managedLua() {
    const m = HyprlandConfig.managed;
    const module = moduleLua().split("\n").filter(line => !line.startsWith("--")).join("\n").trim();
    return `${_header} (Hyprland mode: managed) from its Hyprland settings,
-- and rewritten whenever they (or the theme) change: edit those, not this file.
-- Your own config goes in ${userDir}/*.lua, loaded after this in name
-- order, so it overrides it. hl.unbind("KEY") there frees one of axiom's keys.

local axiom = (function()
${_indent(module.split("\n"), "  ")}
end)()

hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })

hl.config({
  general = { layout = ${_lua(m.layout)}, gaps_in = ${m.gapsIn}, gaps_out = ${m.gapsOut}, border_size = ${m.borderSize}, resize_on_border = ${m.resizeOnBorder} },
  dwindle = { preserve_split = ${m.preserveSplit} },
  decoration = {
    rounding = ${m.rounding},
    dim_inactive = ${m.dimInactive},
    dim_strength = ${m.dimStrength / 100},
    blur = { enabled = ${m.windowBlur}, size = ${m.blurSize}, passes = ${m.blurPasses} },
  },
  animations = { enabled = ${m.animations} },
  input = {
    kb_layout = ${_lua(m.kbLayout)},
    repeat_rate = ${m.repeatRate},
    repeat_delay = ${m.repeatDelay},
    numlock_by_default = ${m.numlockByDefault},
    follow_mouse = ${m.followMouse ? 1 : 0},
    accel_profile = ${_lua(m.accelProfile === "default" ? "" : m.accelProfile)},
    touchpad = { natural_scroll = ${m.naturalScroll} },
  },
})
${_cursorLua(m)}
axiom.setup()

hl.on("hyprland.start", function()
${_indent(_startLua(m), "  ")}
end)

-- Your files, through require (as user.<name>) so Hyprland reloads when
-- one changes. Shared modules go in user/lib/ (require("user.lib.x")),
-- which isn't loaded here. A failing file doesn't stop the rest; the
-- errors are raised together at the end (hyprctl configerrors).
local errors = {}
local files = io.popen("cd " .. ${_lua(_shellWord(userDir))} .. " 2>/dev/null && ls -1 *.lua 2>/dev/null")
if files then
  for file in files:lines() do
    local ok, err = pcall(require, "user." .. file:gsub("%.lua$", ""))
    if not ok then errors[#errors + 1] = tostring(err) end
  end
  files:close()
end
if #errors > 0 then error(table.concat(errors, "\\n")) end
`;
  }

  // --- Keys ---

  readonly property var _modBits: ({
      "SHIFT": 1,
      "CAPS": 2,
      "LOCK": 2,
      "CTRL": 4,
      "CONTROL": 4,
      "ALT": 8,
      "MOD1": 8,
      "MOD2": 16,
      "MOD3": 32,
      "SUPER": 64,
      "WIN": 64,
      "LOGO": 64,
      "MOD4": 64,
      "META": 64,
      "MOD5": 128
    })

  // "SUPER + SHIFT + SPACE" as hyprctl binds lists it ("64:space"), or ""
  function _keyId(key) {
    const parts = String(key).split("+").map(part => part.trim()).filter(part => part !== "");
    if (parts.length === 0)
      return "";
    let mask = 0;
    for (const mod of parts.slice(0, -1)) {
      const bit = _modBits[mod.toUpperCase()];
      if (bit === undefined)
        return "";
      mask |= bit;
    }
    return mask + ":" + parts[parts.length - 1].toLowerCase();
  }

  // --- Runtime (detached, and the fallback) ---

  // Keys this layer bound at runtime live in Hyprland's Lua state
  // (AXIOM_RUNTIME_KEYS), which a config reload resets along with the
  // binds, and which outlives a reload of the shell. They're unbound
  // before the binds are read, so they don't look like the user's.
  readonly property string _unbindLua: "for _, key in ipairs(AXIOM_RUNTIME_KEYS or {}) do hl.unbind(key) end\nAXIOM_RUNTIME_KEYS = nil"
  // Keys skipped as taken, so each is only reported once
  property var _reportedTaken: ({})
  property bool _runtimeWanted: false

  function _applyRuntime() {
    _runtimeWanted = true;
    if (!unbindRuntime.running && !getBinds.running)
      unbindRuntime.running = true;
  }

  function _clearRuntime() {
    _runtimeWanted = false;
    HyprlandManager.runLua(_unbindLua);
  }

  function _finishRuntime(bindList, animations) {
    if (!_runtimeWanted)
      return;
    const taken = new Set(bindList.filter(bind => !bind.submap).map(bind => bind.modmask + ":" + String(bind.key).toLowerCase()));
    const lines = [];
    const keys = [];
    for (const bind of HyprlandConfig.binds) {
      const line = _bindLua(bind);
      const id = _keyId(bind.key);
      if (line === "")
        continue;
      if (id === "") {
        console.warn(`[HyprlandConfigManager] Can't read the key "${bind.key}"; bind it as MODS + KEY`);
        continue;
      }
      if (taken.has(id)) {
        if (!_reportedTaken[id])
          console.log(`[HyprlandConfigManager] ${bind.key} is bound by your Hyprland config; skipping axiom's bind`);
        _reportedTaken[id] = true;
        continue;
      }
      lines.push(line);
      keys.push(bind.key.trim());
    }
    if (HyprlandConfig.requiredSettings) {
      const anim = (Array.isArray(animations?.[0]) ? animations[0] : []).find(a => a.name === "workspaces");
      lines.push(..._requiredLua(!anim?.overridden));
    }
    if (HyprlandConfig.theme)
      lines.push(..._themeLua());
    if (HyprlandConfig.blur)
      lines.push(..._blurLua());
    lines.push(`AXIOM_RUNTIME_KEYS = { ${keys.map(key => _lua(key)).join(", ")} }`);
    HyprlandManager.runLua(lines.join("\n"));
    HyprlandManager.refreshOptions();
  }

  // --- Files (included, managed) ---

  // Writes `text` to `path` unless it's already there; then reloads
  // Hyprland, since it doesn't watch files a config loads
  function _writeIfChanged(path, text) {
    if (FileManager.read(path) === text) {
      _checkLoaded();
      return;
    }
    root._pendingWrite = {
      "path": path,
      "text": text
    };
    makeDir.command = ["mkdir", "-p", path.replace(/\/[^/]*$/, "")];
    makeDir.running = true;
  }

  property var _pendingWrite: null

  Process {
    id: makeDir
    onExited: code => {
      const write = root._pendingWrite;
      root._pendingWrite = null;
      if (code !== 0 || !write) {
        console.warn("[HyprlandConfigManager] Could not create the folder for", write?.path);
        return;
      }
      writer.path = write.path;
      writer.setText(write.text);
    }
  }

  // After a (re)load: is the file in effect? If not, the runtime layer
  // stands in for it
  function _checkLoaded() {
    if (!checkLoaded.running)
      checkLoaded.running = true;
  }

  function _warnOnce(message) {
    if (_problem === message)
      return;
    _problem = message;
    console.warn("[HyprlandConfigManager]", message);
  }

  // --- Driving it ---

  function apply() {
    if (mode === "included") {
      _writeIfChanged(includePath, moduleLua());
    } else if (mode === "managed") {
      if (!claimManaged.running)
        claimManaged.running = true;
    } else {
      _problem = "";
      _applyRuntime();
    }
  }

  // Everything the layer is made of; a change re-applies it
  readonly property string _inputs: [mode, HyprlandConfig._bindsJson, HyprlandConfig._managedJson, HyprlandConfig.requiredSettings, HyprlandConfig.theme, HyprlandConfig.blur, Theme.borderFocus, Theme.border].join("|")
  on_InputsChanged: _debounce.restart()

  property Timer _debounce: Timer {
    interval: 300
    onTriggered: root.apply()
  }

  Component.onCompleted: {
    _debounce.restart();
    if (HyprlandConfig.wallpaperDaemon)
      startWallpaperDaemon.running = true;
  }

  Connections {
    target: Hyprland

    function onRawEvent(event) {
      if (event.name !== "configreloaded")
        return;
      // A reload drops runtime binds and rules
      if (root.mode === "detached")
        root._debounce.restart();
      else
        root._checkLoaded();
    }
  }

  Process {
    id: unbindRuntime
    command: ["hyprctl", "eval", root._unbindLua]
    onExited: getBinds.running = true
  }

  Process {
    id: getBinds
    command: ["hyprctl", "binds", "-j"]
    stdout: StdioCollector {
      id: bindsCollector
      onStreamFinished: {
        try {
          root._bindList = JSON.parse(bindsCollector.text);
        } catch (e) {
          console.warn("[HyprlandConfigManager] Could not parse hyprctl binds:", e);
          root._bindList = [];
        }
        getAnimations.running = true;
      }
    }
  }

  property var _bindList: []

  Process {
    id: getAnimations
    command: ["hyprctl", "animations", "-j"]
    stdout: StdioCollector {
      id: animationsCollector
      onStreamFinished: {
        let animations = null;
        try {
          animations = JSON.parse(animationsCollector.text);
        } catch (e) {
          console.warn("[HyprlandConfigManager] Could not parse hyprctl animations:", e);
        }
        root._finishRuntime(root._bindList, animations);
      }
    }
  }

  // Output "ok" when the file's marker is set in Hyprland's Lua state
  Process {
    id: checkLoaded
    command: ["hyprctl", "eval", "if not AXIOM_INCLUDED then error('axiom: not loaded') end"]
    stdout: StdioCollector {
      id: loadedCollector
      onStreamFinished: {
        if (root.mode === "detached")
          return;
        if (loadedCollector.text.trim() === "ok") {
          root._problem = "";
          root._clearRuntime();
          return;
        }
        if (root.mode === "included")
          root._warnOnce(`Hyprland mode is "included", but hyprland.lua doesn't load ${root.includePath}; add:\n${root.includeLines}`);
        else if (root._problem === "")
          root._warnOnce(`Hyprland mode is "managed", but ${root.managedPath} isn't loaded (see hyprctl configerrors)`);
        root._applyRuntime();
      }
    }
  }

  // Makes ~/.config/hypr/hyprland.lua axiom's: "ours" (already), "adopted"
  // (the old one moved to user/00-previous.lua, a dated backup beside it)
  // or "blocked" (a symlinked or git-tracked config is never taken over)
  Process {
    id: claimManaged
    command: ["sh", "-c", `dir=\${1%/}; file=$dir/hyprland.lua
if [ -f "$file" ] && head -n1 "$file" | grep -q '^${root._header}'; then echo ours; exit 0; fi
if [ -L "$dir" ] || [ -L "$file" ] || git -C "$dir" rev-parse --git-dir >/dev/null 2>&1; then echo blocked; exit 0; fi
mkdir -p "$dir/user" || exit 1
if [ -f "$file" ]; then
  cp -p "$file" "$file.axiom-backup-$(date +%Y%m%d-%H%M%S)" && mv "$file" "$dir/user/00-previous.lua" || exit 1
fi
echo adopted`, "sh", Paths.hyprlandPath]
    stdout: StdioCollector {
      id: claimCollector
      onStreamFinished: {
        const result = claimCollector.text.trim();
        if (result === "blocked") {
          root._warnOnce(`Hyprland mode is "managed", but ${Paths.hyprlandPath} is a symlink or in a git repository, so axiom won't take it over; use "included" instead. Applying axiom's layer at runtime meanwhile.`);
          root._applyRuntime();
          return;
        }
        if (result === "adopted")
          console.log(`[HyprlandConfigManager] Took over ${root.managedPath}; your previous one is ${root.userDir}/00-previous.lua`);
        if (result === "ours" || result === "adopted")
          root._writeIfChanged(root.managedPath, root.managedLua());
      }
    }
    stderr: StdioCollector {
      id: claimErrors
      onStreamFinished: {
        if (claimErrors.text.trim() !== "")
          console.warn("[HyprlandConfigManager] Taking over hyprland.lua:", claimErrors.text.trim());
      }
    }
  }

  FileView {
    id: writer
    atomicWrites: true
    printErrors: false
    onSaved: reload.running = true
    onSaveFailed: error => console.warn("[HyprlandConfigManager] Could not write", writer.path, error)
  }

  Process {
    id: reload
    command: ["hyprctl", "reload"]
  }

  Process {
    id: startWallpaperDaemon
    command: ["sh", "-c", "command -v awww-daemon >/dev/null || exit 0; awww query >/dev/null 2>&1 || setsid -f awww-daemon >/dev/null 2>&1"]
  }
}
