#!/usr/bin/env bash
#
# Quickshell theme -> a local VS Code / VSCodium color theme extension.
#
# Usage: theme_vscode.sh <theme.json> [extension_dir]
#   output: axiom-theme/ in ~/.vscode/extensions and/or ~/.vscode-oss/extensions (whichever editor has run)
#   hookup: pick the "Axiom" color theme (Preferences: Color Theme)
#   reload: open windows on "Developer: Reload Window"
#
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/theme_env.sh"
usage_or_help 3 8 "$@"
require_cmds jq

if [ $# -ge 2 ]; then
    TARGETS=("$2")
else
    TARGETS=()
    for PROFILE in "$HOME/.vscode" "$HOME/.vscode-oss"; do
        [ -d "$PROFILE" ] && TARGETS+=("$PROFILE/extensions/axiom-theme")
    done
    if [ ${#TARGETS[@]} -eq 0 ]; then
        echo "Error: neither ~/.vscode nor ~/.vscode-oss exists (start VS Code or VSCodium once)." >&2
        exit 1
    fi
fi
load_theme "$1"
export_theme_colors
UI_THEME=$([[ "$THEME_VARIANT" == "light" ]] && echo vs || echo vs-dark)

# Every exported color, for jq ($c.ACCENT, $c.ANSI_0, ...)
COLORS_JSON=$(for var in $(theme_color_vars); do printf '%s\t%s\n' "$var" "${!var}"; done |
    jq -Rn '[inputs | split("\t") | {(.[0]): .[1]}] | add')

THEME_JSON=$(jq -n --argjson c "$COLORS_JSON" --arg name "$THEME_NAME" --arg type "${UI_THEME#vs-}" '{
    name: "Axiom",
    type: (if $type == "vs" then "light" else "dark" end),
    "$comment": "Generated by axiom (scripts/theme_vscode.sh) from the \($name) theme. Rewritten on every theme change.",
    colors: {
        "foreground": $c.FOREGROUND,
        "focusBorder": $c.BORDER_FOCUS,
        "selection.background": $c.BACKGROUND_HIGHLIGHT,
        "widget.border": $c.BORDER,
        "editor.background": $c.BACKGROUND,
        "editor.foreground": $c.FOREGROUND,
        "editor.lineHighlightBackground": $c.BACKGROUND_ALT,
        "editor.selectionBackground": $c.BACKGROUND_HIGHLIGHT,
        "editor.findMatchHighlightBackground": ($c.WARNING + "55"),
        "editorCursor.foreground": $c.ACCENT,
        "editorLineNumber.foreground": $c.FOREGROUND_INACTIVE,
        "editorLineNumber.activeForeground": $c.ACCENT,
        "editorIndentGuide.background1": $c.BACKGROUND_HIGHLIGHT,
        "editorWhitespace.foreground": $c.BACKGROUND_HIGHLIGHT,
        "editorError.foreground": $c.ERROR,
        "editorWarning.foreground": $c.WARNING,
        "editorInfo.foreground": $c.INFO,
        "editorGutter.addedBackground": $c.SUCCESS,
        "editorGutter.deletedBackground": $c.ERROR,
        "editorGutter.modifiedBackground": $c.WARNING,
        "editorWidget.background": $c.BACKGROUND_ALT,
        "editorGroupHeader.tabsBackground": $c.BACKGROUND_ALT,
        "tab.activeBackground": $c.BACKGROUND,
        "tab.activeForeground": $c.FOREGROUND,
        "tab.activeBorderTop": $c.ACCENT,
        "tab.inactiveBackground": $c.BACKGROUND_ALT,
        "tab.inactiveForeground": $c.FOREGROUND_INACTIVE,
        "tab.border": $c.BACKGROUND_ALT,
        "activityBar.background": $c.BACKGROUND_ALT,
        "activityBar.foreground": $c.FOREGROUND,
        "activityBar.inactiveForeground": $c.FOREGROUND_INACTIVE,
        "activityBarBadge.background": $c.ACCENT,
        "activityBarBadge.foreground": $c.BACKGROUND,
        "sideBar.background": $c.BACKGROUND_ALT,
        "sideBar.foreground": $c.FOREGROUND,
        "sideBarSectionHeader.background": $c.BACKGROUND_ALT,
        "list.activeSelectionBackground": $c.BACKGROUND_HIGHLIGHT,
        "list.activeSelectionForeground": $c.FOREGROUND_HIGHLIGHT,
        "list.hoverBackground": $c.BACKGROUND_HIGHLIGHT,
        "list.highlightForeground": $c.ACCENT,
        "titleBar.activeBackground": $c.BACKGROUND_ALT,
        "titleBar.activeForeground": $c.FOREGROUND,
        "titleBar.inactiveBackground": $c.BACKGROUND_ALT,
        "titleBar.inactiveForeground": $c.FOREGROUND_INACTIVE,
        "statusBar.background": $c.BACKGROUND_ALT,
        "statusBar.foreground": $c.FOREGROUND,
        "statusBar.noFolderBackground": $c.BACKGROUND_ALT,
        "statusBar.debuggingBackground": $c.WARNING,
        "statusBar.debuggingForeground": $c.BACKGROUND,
        "panel.background": $c.BACKGROUND,
        "panel.border": $c.BORDER,
        "panelTitle.activeBorder": $c.ACCENT,
        "input.background": $c.BACKGROUND,
        "input.border": $c.BORDER,
        "input.foreground": $c.FOREGROUND,
        "dropdown.background": $c.BACKGROUND_ALT,
        "button.background": $c.ACCENT,
        "button.foreground": $c.BACKGROUND,
        "badge.background": $c.ACCENT,
        "badge.foreground": $c.BACKGROUND,
        "progressBar.background": $c.ACCENT,
        "textLink.foreground": $c.ACCENT,
        "gitDecoration.addedResourceForeground": $c.SUCCESS,
        "gitDecoration.modifiedResourceForeground": $c.WARNING,
        "gitDecoration.deletedResourceForeground": $c.ERROR,
        "gitDecoration.untrackedResourceForeground": $c.INFO,
        "terminal.background": $c.BACKGROUND,
        "terminal.foreground": $c.FOREGROUND,
        "terminalCursor.foreground": $c.ACCENT,
        "terminal.ansiBlack": $c.ANSI_0, "terminal.ansiRed": $c.ANSI_1,
        "terminal.ansiGreen": $c.ANSI_2, "terminal.ansiYellow": $c.ANSI_3,
        "terminal.ansiBlue": $c.ANSI_4, "terminal.ansiMagenta": $c.ANSI_5,
        "terminal.ansiCyan": $c.ANSI_6, "terminal.ansiWhite": $c.ANSI_7,
        "terminal.ansiBrightBlack": $c.ANSI_8, "terminal.ansiBrightRed": $c.ANSI_9,
        "terminal.ansiBrightGreen": $c.ANSI_10, "terminal.ansiBrightYellow": $c.ANSI_11,
        "terminal.ansiBrightBlue": $c.ANSI_12, "terminal.ansiBrightMagenta": $c.ANSI_13,
        "terminal.ansiBrightCyan": $c.ANSI_14, "terminal.ansiBrightWhite": $c.ANSI_15
    },
    tokenColors: [
        { scope: ["comment", "punctuation.definition.comment"], settings: { foreground: $c.FOREGROUND_INACTIVE, fontStyle: "italic" } },
        { scope: ["string"], settings: { foreground: $c.GREEN } },
        { scope: ["string.regexp", "constant.character.escape"], settings: { foreground: $c.CYAN } },
        { scope: ["constant.numeric", "constant.language", "constant.character", "constant.other"], settings: { foreground: $c.ORANGE } },
        { scope: ["keyword", "storage.type", "storage.modifier"], settings: { foreground: $c.MAGENTA } },
        { scope: ["keyword.operator", "punctuation"], settings: { foreground: $c.FOREGROUND_ALT } },
        { scope: ["entity.name.function", "support.function", "meta.function-call"], settings: { foreground: $c.BLUE } },
        { scope: ["entity.name.type", "entity.name.class", "support.type", "support.class"], settings: { foreground: $c.YELLOW } },
        { scope: ["variable"], settings: { foreground: $c.FOREGROUND } },
        { scope: ["variable.parameter"], settings: { foreground: $c.FOREGROUND_ALT, fontStyle: "italic" } },
        { scope: ["variable.language"], settings: { foreground: $c.RED } },
        { scope: ["entity.name.tag"], settings: { foreground: $c.RED } },
        { scope: ["entity.other.attribute-name"], settings: { foreground: $c.YELLOW } },
        { scope: ["entity.name.namespace", "entity.name.module"], settings: { foreground: $c.CYAN } },
        { scope: ["invalid"], settings: { foreground: $c.ERROR } },
        { scope: ["markup.heading", "entity.name.section"], settings: { foreground: $c.ACCENT, fontStyle: "bold" } },
        { scope: ["markup.bold"], settings: { fontStyle: "bold" } },
        { scope: ["markup.italic"], settings: { fontStyle: "italic" } },
        { scope: ["markup.underline.link"], settings: { foreground: $c.BLUE } },
        { scope: ["markup.inserted"], settings: { foreground: $c.SUCCESS } },
        { scope: ["markup.deleted"], settings: { foreground: $c.ERROR } },
        { scope: ["markup.changed"], settings: { foreground: $c.WARNING } }
    ]
}')
# uiTheme follows the variant, so the manifest is rewritten too
PACKAGE_JSON=$(jq -n --arg ui "$UI_THEME" '{
    name: "axiom-theme", displayName: "Axiom", publisher: "axiom", version: "1.0.0",
    description: "The active axiom shell theme (generated; rewritten on every theme change)",
    engines: { vscode: "^1.60.0" }, categories: ["Themes"],
    contributes: { themes: [{ label: "Axiom", uiTheme: $ui, path: "./themes/axiom-color-theme.json" }] }
}')

for DIR in "${TARGETS[@]}"; do
    echo "$THEME_JSON" | write_atomic "$DIR/themes/axiom-color-theme.json"
    echo "$PACKAGE_JSON" | write_atomic "$DIR/package.json"
    echo "✅ Written to '$DIR'"
done
