pragma ComponentBehavior: Bound
import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
import qs.config
import qs.services
import qs.components.reusable
import qs.components.forms
import qs.components.content.base

PanelCard {
  id: root

  property var localConfig: SettingsManager.localConfig

  title: I18n.tr("Theme")
  dirty: SettingsManager.isDirty
  onSave: SettingsManager.saveChanges()
  onReset: SettingsManager.resetChanges()

  Item {
    Layout.preferredHeight: Widget.spacing
  }

  // TODO: Control whether or not pywal is used with below toggle, and have the user select a backend.
  // SchemaSwitch {
  //   label: "Enable Generated Theme"
  //   description: "Automatically apply themes generated by pywal."
  //   checked: root.localConfig.Appearance?.enableGeneratedTheme || false
  //   onToggled: value => {
  //     if (value === checked) return;
  //     if (!root.localConfig.Appearance)
  //       root.localConfig.Appearance = {};
  //     root.localConfig.Appearance.enableGeneratedTheme = value;
  //     SettingsManager.markDirty();
  //     SettingsManager.applyChanges();
  //   }
  // }

  SchemaSection {
    id: pywalThemes
    title: I18n.tr("Generated Themes")
    expanded: false
    Layout.leftMargin: Widget.padding
    Layout.rightMargin: Widget.padding

    ListView {
      id: generatedThemeListView
      Layout.fillWidth: true
      Layout.preferredHeight: contentHeight
      model: ThemeManager.generatedThemes
      spacing: Widget.spacing / 2
      delegate: StyledTextButton {
        required property var modelData
        visible: modelData.name.includes("dark")
        height: visible ? implicitHeight : 0
        width: parent.width
        text: modelData.name.replace("dark-", "").replace("light-", "")
        backgroundColor: Appearance.theme === modelData.name ? Theme.accent : Theme.backgroundHighlight
        textHoverColor: Appearance.theme === modelData.name ? Theme.foreground : Theme.background

        onClicked: ThemeManager.applyTheme(modelData.name, true)
      }
    }
  }

  // SchemaObjectArray {
  //   label: "Pywal Backend"
  //   property var backendOptions: ["colorthief", "wal", "colorz", "pywal"]
  //   label: "Pywal Backend"
  //   items: backendOptions
  // }

  SchemaSwitch {
    label: I18n.tr("Enable Light Mode")
    description: I18n.tr("Toggle light mode for supported themes.")
    checked: !Appearance.darkMode || false
    onToggled: value => {
      ThemeManager.toggleDarkMode();
    }
  }

  SchemaSection {
    id: userThemes
    title: I18n.tr("User Themes")
    Layout.leftMargin: Widget.padding
    Layout.rightMargin: Widget.padding
  }

  SchemaSection {
    id: defaultThemes
    title: I18n.tr("Default Themes")
    Layout.leftMargin: Widget.padding
    Layout.rightMargin: Widget.padding

    ListView {
      id: defaultThemeListView
      Layout.fillWidth: true
      Layout.preferredHeight: contentHeight
      model: ThemeManager.defaultThemes
      spacing: Widget.spacing / 2
      delegate: StyledTextButton {
        required property var modelData
        width: parent.width
        text: modelData.name
        backgroundColor: Appearance.theme === modelData.name ? Theme.accent : Theme.backgroundHighlight
        textHoverColor: Appearance.theme === modelData.name ? Theme.foreground : Theme.background

        onClicked: ThemeManager.applyTheme(modelData.name, false)
      }
    }
  }
}
